// We import StrictMode from React — it helps catch bugs during development
import { StrictMode } from 'react'

// createRoot is what actually starts my React app in the browser
import { createRoot } from 'react-dom/client'

// RouterProvider displays the right page, createRouter builds the router
import { RouterProvider, createRouter } from '@tanstack/react-router'

// This file will be auto-generated by TanStack — it connects all my routes
import { routeTree } from './routeTree.gen'

// Our global styles with Tailwind and DaisyUI
import './index.css'

// I create the router and give it my routeTree (all my pages/routes)
const router = createRouter({ routeTree })

// I find the <div id="root"> in index.html and start my React app inside it
createRoot(document.getElementById('root')!).render(
  // StrictMode wraps everything — only active in development, not in production
  <StrictMode>
    {/* RouterProvider runs the router and shows the correct page */}
    <RouterProvider router={router} />
  </StrictMode>,
)