/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsDestinationIdRouteImport } from './routes/destinations/$destinationId'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsDestinationIdRoute =
  DestinationsDestinationIdRouteImport.update({
    id: '/destinations/$destinationId',
    path: '/destinations/$destinationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/destinations/$destinationId': typeof DestinationsDestinationIdRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/destinations/$destinationId': typeof DestinationsDestinationIdRoute
  '/destinations': typeof DestinationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/destinations/$destinationId': typeof DestinationsDestinationIdRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/impressum'
    | '/destinations/$destinationId'
    | '/destinations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/impressum'
    | '/destinations/$destinationId'
    | '/destinations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/impressum'
    | '/destinations/$destinationId'
    | '/destinations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImpressumRoute: typeof ImpressumRoute
  DestinationsDestinationIdRoute: typeof DestinationsDestinationIdRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$destinationId': {
      id: '/destinations/$destinationId'
      path: '/destinations/$destinationId'
      fullPath: '/destinations/$destinationId'
      preLoaderRoute: typeof DestinationsDestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImpressumRoute: ImpressumRoute,
  DestinationsDestinationIdRoute: DestinationsDestinationIdRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
